### ISSUE TITLE
paper preprint?

### ISSUE THREAD

**Issue by Mike-Huang01** [webis-de/ecir21-an-empirical-comparison-of-web-page-segmentation-algorithms#1]
If the referenced paper had been publised or there is a preprinted version, please list it on README page.
THX!

**Comment by johanneskiesel** [comment]
Hi Mike, the paper is currently still in (single-blind) review and I would want to wait for the decision before publishing a version. But you can send me a mail at johannes.kiesel@uni-weimar.de and I can send you a preprint.

**Comment by Mike-Huang01** [comment]
> Hi Mike, the paper is currently still in (single-blind) review and I would want to wait for the decision before publishing a version. But you can send me a mail at [johannes.kiesel@uni-weimar.de](mailto:johannes.kiesel@uni-weimar.de) and I can send you a preprint.

Thx for your kindess!
